accumulate_grad_batches: 32
amp_level: O0
balance_test: false
balance_train: true
balance_val: true
base_number: 10
check_val_every_n_epoch: 2
gamma: 1.0
gpus: 1
gradient_clip_val: 1.0
invert_answer: false
invert_question: false
lr: 0.0003
max_digits_test: 15
max_digits_train: 15
max_epochs: 20
max_seq_length: 512
min_digits_test: 2
min_digits_train: 2
model_name_or_path: t5-base
num_workers: 4
operation: addition
optimizer: AdamW
orthography: 10ebased
output_dir: ./output
precision: 32
scheduler: StepLR
seed: 1
step_size: 1000
t_0: 2
t_mult: 2
test_size: 10000
train_batch_size: 4
train_size: 100000
val_batch_size: 32
val_size: 10000
weight_decay: 5.0e-05
